services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5432:5432' # Porta da máquina <- Porta do container
    volumes:
      -  ./data:/var/lib/postgresql/data # Espelhando arquivos para da máquina local, garantindo consistencia. Pasta local <- Pasta do container
    networks:
      - imagelitenetwork

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com #Aqui por ser uma image existente, coloco dessa forma
    ports:
      - '15432:80'
    depends_on:
      - db
    networks:
      - imagelitenetwork

  springbootapp:
    build:
      dockerfile: Dockerfile
      context: ./imageliteapi
    container_name: imageliteapi
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - imagelitenetwork
    environment:
      - "POSTGRES_HOST=db" #Por ser uma image custom, preciso colocar dessa forma a variavel
    
  reactapp:
    build:
      dockerfile: Dockerfile
      context: ./imagelite
    container_name: imageliteapp
    restart: on-failure
    depends_on:
      - springbootapp
    ports:
      - '3000:3000'
    networks:
      - imagelitenetwork
    expose:
      - 3000


networks:
  imagelitenetwork:
    driver: bridge
